return {}
-- return {
--   "nvim-tree/nvim-tree.lua",
--   version = "*",
--   lazy = false,
--   dependencies = {
--     "nvim-tree/nvim-web-devicons",
--   },
--   config = function()
--     require("nvim-tree").setup({
--       hijack_directories = {
--          auto_open = false,
--       },
--     })
--   end,
-- }
